PROJECT_NAME = "COVID-19 Vaccine Availability Notifier"
DEFAULT_LOG_LEVEL = "INFO"
CONFIG_FILE_NAME = "config.json"
API_PREFIX = "/api"
API_TITLE = "COVID-19 Vaccine Availability Notifier"
API_VERSION = "1.0.0"
API_DOCS_URL = "/docs"
INTERNAL_SERVER_ERROR_STRING = "Something went wrong"
BACKEND_FILE_PATH = "./static/backend_file.json"
MIN_AGE_LIMIT = 18
POLL_INTERVAL = 60 * 2
DUMMY_EMAIL = "username@domain.com"
DUMMY_PASSWORD = "super@secret@password"
